version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/MoaRoom-Front
    overwrite: yes

permissions:
  - object: /home/ubuntu/MoaRoom-Front
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu